# Extends the mainnet preset
PRESET_BASE: 'mainnet'
CONFIG_NAME: 'nephele'

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 6  # TBD
# Example date for illustration, replace with actual genesis time
MIN_GENESIS_TIME: 1655647200  # Keep the original value for example purposes
GENESIS_FORK_VERSION: 0x90000069  # Keep original as a placeholder
GENESIS_DELAY: 86400  # Standard delay

# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x90000070  # Original value as placeholder
ALTAIR_FORK_EPOCH: 50  # Original epoch

# Merge
BELLATRIX_FORK_VERSION: 0x90000071  # Original value as placeholder
BELLATRIX_FORK_EPOCH: 100  # Original epoch
TERMINAL_TOTAL_DIFFICULTY: 17000000000000000  # Original difficulty
TERMINAL_BLOCK_HASH: 0x0000000000000000000000000000000000000000000000000000000000000000  # Example hash
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 18446744073709551615  # Example epoch

# Capella
CAPELLA_FORK_VERSION: 0x90000072  # Original value as placeholder
CAPELLA_FORK_EPOCH: 56832  # Original epoch

# Deneb
DENEB_FORK_VERSION: 0x90000073  # Original value as placeholder
DENEB_FORK_EPOCH: 132608  # Original epoch

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: 12  # Original timing
SECONDS_PER_ETH1_BLOCK: 14  # Estimate from Eth1 mainnet
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256  # Original delay
SHARD_COMMITTEE_PERIOD: 256  # Original period
ETH1_FOLLOW_DISTANCE: 2048  # Original distance

# Validator cycle
# ---------------------------------------------------------------
INACTIVITY_SCORE_BIAS: 4  # Original score bias
INACTIVITY_SCORE_RECOVERY_RATE: 16  # Original recovery rate
EJECTION_BALANCE: 16000000000  # Original balance
MIN_PER_EPOCH_CHURN_LIMIT: 4  # Original churn limit
CHURN_LIMIT_QUOTIENT: 65536  # Original quotient
MAX_PER_EPOCH_ACTIVATION_CHURN_LIMIT: 8  # New in Deneb:EIP7514

# Fork choice
# ---------------------------------------------------------------
PROPOSER_SCORE_BOOST: 40  # Original boost percentage

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 11155111  # Original chain ID
DEPOSIT_NETWORK_ID: 11155111  # Original network ID
DEPOSIT_CONTRACT_ADDRESS: 0x7f02C3E3c98b133055B8B348B2Ac625669Ed295D  # Original address

# Networking
# ---------------------------------------------------------------
GOSSIP_MAX_SIZE: 10485760  # 10 MiB
MAX_REQUEST_BLOCKS: 1024  # Original max
EPOCHS_PER_SUBNET_SUBSCRIPTION: 256  # Original subscription period
MIN_EPOCHS_FOR_BLOCK_REQUESTS: 33024  # Calculation based on delay and quotient
MAX_CHUNK_SIZE: 10485760  # 10 MiB
TTFB_TIMEOUT: 5  # Time to first byte timeout
RESP_TIMEOUT: 10  # Response timeout
ATTESTATION_PROPAGATION_SLOT_RANGE: 32  # Original slot range
MAXIMUM_GOSSIP_CLOCK_DISPARITY: 500  # Maximum allowed clock disparity
MESSAGE_DOMAIN_INVALID_SNAPPY: 0x00000000  # Original domain
MESSAGE_DOMAIN_VALID_SNAPPY: 0x01000000  # Original domain
SUBNETS_PER_NODE: 2  # Original subnet allocation
ATTESTATION_SUBNET_COUNT: 64  # Original subnet count
ATTESTATION_SUBNET_EXTRA_BITS: 0  # Original extra bits
ATTESTATION_SUBNET_PREFIX_BITS: 6  # Calculated from subnet count

# Deneb
MAX_REQUEST_BLOCKS_DENEB: 128  # Original Deneb value
MAX_REQUEST_BLOB_SIDECARS: 768  # Calculated based on Deneb blocks
MIN_EPOCHS_FOR_BLOB_SIDECARS_REQUESTS: 4096  # Original value for Deneb
BLOB_SIDECAR_SUBNET_COUNT: 6  # Original subnet count for Deneb